---
title: "Workshop Schedule"
author: 2017 International Biogeography Meeting
---

|  Time  |  Presenters  |  Title   
|--------|:-------------|:-----------------------------------------------------|
| 100-120 | Cory Merow <br> Rob Anderson <br> Brian Enquist | Welcome <br> Downloads |
| 120-140 | Brian Enquist | Introduction BIEN - The Botanical Information and Ecology Network ([bien3.org](bien3.org))  |
| 140-200 | Brian McGill  | Dirty Data |
| 200-220 | Brad Boyle    | Taxonomic Name Resolution Service |
| 220-230 | Break         | |
| 230-250 | Brian Maitner | Accessing New World plant data: `RBien` |
| 250-300 | Rob Anderson <br> Jamie Kass | Wallace - An R-based reproducible workflow for ecological analyses |
| 300-340 | Jamie Kass <br> Matt Aiello-Lammens | `wallace` Demo |
| 340-400 | Cory Merow    | Integrating biogeographic data with other spatial maps: `bossMaps` |
| 400-420 | Naia Morueta-Holme | Species network associations: `netassoc` |
| 420-440 | Drew Kerkhoff | Teaching ecoinformatics to undergrads |
| 440-500 | Rob Anderson <br> Cory Merow | Future Directions |



While you're waiting, please :

Sign up for an account to access [bien3.org](bien3.org)

```{r,eval=FALSE}
install.packages(c('devtools', 'netassoc'),dep=T)
install.packages(c('ape','sp','maps'),dep=T)
install.packages(c('bossMaps','ggplot2','foreach', 'dplyr','tidyr','raster'),dep=T)
install.packages('rgdal', 'mapdata','dismo','rJava' ,'maptools','jsonlite',dep=T)
devtools::install_github("wallaceEcoMod/wallace")
install.packages('ape','rjson','RCurl')

```
<!--
Wallace: install_github()?
RBEIN:install_github("EnquistLab/RBIEN/BRI")
-->

<div>
<object data="3_1_assets/Intro_slides.pdf" type="application/pdf" width="100%" height="650px"> 
  <p>It appears you don't have a PDF plugin for this browser.
   No biggie... you can <a href="3_1_assets/Intro_slides.pdf">click here to
  download the PDF file.</a></p>  
 </object>
 </div>
 
 <p><a href="3_1_assets/Intro_slides.pdf">Download the PDF of the presentation</a></p>  

