---
title: "Course Schedule"
toc: false
---

Course content is designed to be flexible to accommodate student interest and abilities. 


| Date    | Location    | Time      |  Title     | Description |  
|:--|:----|:-------|:------|:----------------------------------------|
| Tues, Nov 29   | ESC110 | 4-530pm |  **Spatial Data Analysis with R** | We'll use spatial data to introduce fundamental concepts for the R programming language and teach best coding practices useful for beginners and experienced alike. Goals include: (1) Experience useful for future, more specific workshops with BGC; (2) Setting up a workflow to make sure coding isn't annoying; (3) Loops; (4) Writing functions; (5) Using raster (spatial) data; (6) Customizable pretty plots.|   
| Mon, Jan 9 | Tucson, AZ | 1-5pm |  **Integrating and cleaning biodiversity data** | A workshop at the International Biogeography Society meeting. [Course details]( https://tucson2017ibs.wordpress.com/workshops/integrating-and-cleaning-biodiversity-data-workflows-to-model-ranges-and-merge-associated-ecological-phylogenetic-and-trait-information/) | 
| Thurs, Jan 26 | ESC110 | 4-530pm |  **Mapping Species Ranges** | We’ll use a complete workflow – from data download to pretty maps of predictions – to model a species geographic distribution (range). Goals include learning how to use:(1) Understand modeling decisions; (2) Statistical regression techniques; (3) Machine learning techniques; (4) Manipulate rasters; (5) Customize plots; (6) Write a workflow that others can use.|



