---
title: "Course Schedule"
---

Course content is designed to be flexible to accommodate student interest and abilities. 


| Date    | Time    | Location    |  Title     | Description |  
|:--|:----|:----|:----|:----------------------------------------|
| Tues, Nov 29   | ESC110 | 4-530pm |  **Spatial Data Analysis with R** | We'll use spatial data to introduce fundamental concepts for the R programming language and teach best coding practices useful for beginners and experienced alike. Goals include: (1) Experience useful for future, more specific workshops with BGC; (2) Setting up a workflow to make sure coding isn't annoying; (3) Loops; (4) Writing functions; (5) Using raster (spatial) data; (6) Customizable pretty plots.|   
| Thurs, Jan 26 | ESC110 | 4-530pm |  **Mapping Species Ranges** | We’ll use a complete workflow – from data download to pretty maps of predictions – to model a species geographic distribution (range). Goals include learning how to use:(1) Understand modeling decisions; (2) Statistical regression techniques; (3) Machine learning techniques; (4) Manipulate rasters; (5) Customize plots; (6) Write a workflow that others can use.| 



<!-- 
| Date    | Time  | Location  | Title   | Description |
|:--|:-----|:----|:---------|:-----------------------------------------------------|
| Tues, Nov 29 | 4-530pm | ESC110  | **Spatial Data Analysis with R** | 
We'll use spatial data to introduce fundamental concepts for the R programming language and teach best coding practices useful for beginners and experienced alike. Goals include: (1) Experience useful for future, more specific workshops with BGC; (2) Setting up a workflow to make sure coding isn't annoying; (3) Loops; (4) Writing functions; (5) Using raster (spatial) data; (6) Customizable pretty plots.|   

| Thurs, Jan 26 | 4-530pm | ESC110  | **Mapping Species Ranges** | We’ll use a complete workflow – from data download to pretty maps of predictions – to model a species geographic distribution (range). Goals include learning how to use:(1) Understand modeling decisions; (2) Statistical regression techniques; (3) Machine learning techniques; (4) Manipulate rasters; (5) Customize plots; (6) Write a workflow that others can use.

| 9/12 | **Data Wrangling ** | Data structures (vectors, matrices, data frames). Base graphics. Reading and writing data (from disk and internet). |  Practice homework submitted during class. |
| 9/19 | **Data Wrangling 2** | Filtering, selecting, joining data sets. Data gymnastics with dplyr. |  Homework #1  |
| 9/26 | **Graphics** | More base graphics (scatterplots, histograms).  The _grammar of graphics_: ggplot2 and extensions (ggmap, rasterVis, etc.). |  |
| 10/3 | **Spatial Data** | Spatial Libraries: raster, sp, rgeos, rgdal. Integrating ‘traditional GIS’ analyses with statistical modelling.  Data intersection (e.g. connecting points with polygons and rasters), overlays, zonal statistics | Homework # 2 |
| 10/10 | **Spatial Raster I** | Working with gridded spatial data | Project Proposal Due |
| 10/17 | **Spatial Raster II** | Raster calculations, working with climate datasets.  | Homework # 3    |
| 10/24 | **Spatial Raster III** | A 'mini' project - looking at sea level rise in Bangladesh | |
| 10/31 | **Reproducible Research & Literate Programming & Version Control** | RMarkdown to create dynamic research outputs.  Publishing to github/word/html/etc. Managing code with "version control"" using Github. Figshare and other data repositories. |  |
| 11/7 | **Weather/Climate Data Processing ** | Processing daily weather data from NOAA  |  First draft of project for peer assessment   |
| 11/14 | **Satellite Data Processing** | Working with MODIS Satellite data | Peer Evaluation Due |
| 11/21 | **High Performance Computing & Software Integration** | Parallel processing and high performance computing in R, Calling other programs from within R. | Homework # 4 |
| 11/28 |  **Package Development** |  Package structure and necessary components.  Things to consider when developing an R package. [HTML Widgets](http://www.htmlwidgets.org) | Second draft of project |
| 12/5 | **Final Project Presentations** | | |
-->
