---
title: "Ecology, Statistics, and Data Science with R"
subtitle: "A workshop series for Yale's Center for Biodiversity and Global Change "
---

<a href="https://cmerow.github.io"> Cory Merow</a><br>
Department of Ecology and Evolutionary Biology <br> 
Yale University, New Haven, CT

## Description
The quantity and quality of data available for ecological and environmental research has exploded over the past few decades. These ‘big data’ now allow us to address important questions (both old and new) with unprecedented rigor and generality.  Leveraging these new data streams requires new tools and increasingly sophisticated workflows. The free and open-source R programming language has become a lingua franca for ecological, epidemiological, and statistical research.  The course will use a combination of lecture and hands-on exercises to provide a gentle introduction to programming in R with a focus on spatial data processing.  The use of ‘literate programming’ (code embedded within text) to generate dynamic, reproducible research output (figures, manuscripts, websites, etc.) will also be addressed. The course includes an extensive project for students to conduct spatial analysis related to their research. Familiarity with basic GIS concepts (raster, vector, geographic projection, etc.) will be assumed, but no prior experience with R is necessary.  The course is open to advanced undergraduate students and graduate students (postdocs are also welcome) with an interest in advancing their data analysis and modeling skill-set. 

Note that the vast majority of the content of this page is adapted from excellent materials developed by <a href="http://adamwilson.us/"> Adam Wilson </a><br> at the University of Buffalo. Please see his course <a href="http://adamwilson.us/RDataScience/"> website </a><br> for many more lessons with the same format.
